kind: ConfigMap
apiVersion: v1
metadata:
  name: bookinfo.dc-%%dcname%%.mcd.bd.f5.com
  namespace: %%application%%
  labels:
    f5type: virtual-server
data:
  # schema v.0.1.4 is required as of k8s-bigip-ctlr v1.3.0
  schema: "f5schemadb://bigip-virtual-server_v0.1.4.json"
  data: |
    {
      "virtualServer": {
        "backend": {
          "serviceName": "productpage",
          "servicePort": 9080
        },
        "frontend": {
          "partition": "%%application%%",
          "iapp": "/Common/os.route",
          "iappPoolMemberTable": {
            "name": "pool__members",
            "columns": [
                {"name": "addr", "kind": "IPAddress"},
                {"name": "port", "kind": "Port"},
                {"name": "connection_limit", "value": "0"},
                {"name": "ratio", "value": "1"}
            ]
          },
          "iappOptions": {
            "description": "L7 route iApp",
            "trafficGroup": "/Common/traffic-group-local-only"
          },
          "iappVariables": {
            "var__policy_path": "/%%application%%/bookinfo-routing-policy",
            "var__dc_host": "bookinfo.dc-%%dcname%%.mcd.bd.f5.com",
            "var__gslb_host": "bookinfo.mcd.bd.f5.com",
            "var__uri": "/",
            "monitor__http_or_https": "http",
            "monitor__interval": "5",
            "monitor__timeout": "16",
            "monitor__request": "GET / HTTP/1.1\\r\\nHost: bookinfo.dc-%%dcname%%.mcd.bd.f5.com",
            "monitor__response": "HTTP/1.[01] 200 O[Kk]",
            "routestatus__routingvip": "%%routingvip_translation%%",
            "routestatus__interval": "15",
            "routestatus__timeout": "16",
            "routestatus__bigipaddr": "localhost",
            "routestatus__bigipport": "%%f5_server_port%%",
            "routestatus__bigipuser": "%%bigip_user%%",
            "routestatus__bigippasswd": "%%bigip_adminpass%%",
            "routestatus__bigipdebug": "On",
            "pool__slow_ramp_setvalue": "30",
            "pool__min_active_members": "1",
            "pool__lb_method": "least-sessions",
            "pool__tcp_queue_enabled_or_disabled": "disabled",
            "pool__tcp_queue_length": "50",
            "pool__tcp_queue_timeout": "500"
          }
        }
      }
    }

