apiVersion: v1
kind: ReplicationController
metadata:
  name: default-backend
spec:
  replicas: 1
  selector:
    app: default-backend
  template:
    metadata:
      name: default-backend
      labels:
        app: default-backend
    spec:
      containers:
      - name: default-backend
        image: k8s.gcr.io/echoserver:1.4
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: default-backend
spec:
  selector:
    app: default-backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

