kind: ConfigMap
apiVersion: v1
metadata:
  name: routing-vip 
  namespace: %%application%%
  labels:
    f5type: virtual-server
data:
  # schema v.0.1.4 is required as of k8s-bigip-ctlr v1.3.0
  schema: "f5schemadb://bigip-virtual-server_v0.1.4.json"
  data: |
    {
      "virtualServer": {
        "backend": {
          "serviceName": "default-backend",
          "servicePort": 8080
        },
        "frontend": {
          "partition": "%%application%%",
          "iapp": "/Common/os.routing-vip",
          "iappPoolMemberTable": {
            "name": "pool__members",
            "columns": [
                {"name": "addr", "kind": "IPAddress"},
                {"name": "port", "kind": "Port"},
                {"name": "connection_limit", "value": "0"}
            ]
          },
          "iappOptions": {
            "description": "os.routing-vip iApp",
            "trafficGroup": "/Common/traffic-group-local-only"
          },
          "iappVariables": {
            "var__prefix": "%%application%%",
            "var__vs_addr": "%%routingvip_translation%%",
            "var__vs_port": "%%routingvip_port_translation%%"
          }
        }
      }
    }

