- hosts: localhost
  gather_facts: no
  vars_files:
    - "vars/common.yaml"
    - "vars/appStates.current.yaml"
  roles: 

    - config-retrieve-params-publish-global
    - config-create-requested-state-publish-global
