---

- name: prepare monitor JSON objects, copy the template file
  delegate_to: localhost
  shell: |
    set -e
    cp "files.input/f5aas-gslb-monitor.tmpl.json" "files.output/gslb-{{GSLB_ZONE}}/f5aas-gslb-monitor_{{ item.uriHost }}.json"

- name: prepare monitor JSON objects, parametrize the template file
  delegate_to: localhost
  replace:
    path: "files.output/gslb-{{GSLB_ZONE}}/f5aas-gslb-monitor_{{ item.uriHost }}.json"
    regexp: "{{ inner.expr }}"
    replace: "{{ inner.replace }}"
  with_items:
      - { expr: '%%uriHost%%', replace: "{{item.uriHost}}" }
      - { expr: '%%uriHostNormalized%%', replace: "{{item.uriHostNormalized}}" }
      - { expr: '%%monitorTypeGslb%%', replace: "{{item.monitorTypeGslb}}" }
      - { expr: '%%sendString%%', replace: "{{item.sendString}}" }
      - { expr: '%%receiveString%%', replace: "{{item.receiveString}}" }
  loop_control:
    loop_var: inner

- name: add monitor JSON document
  include_tasks: library/json-add-dict-element.yaml
  vars:
    node: "files.output/gslb-{{GSLB_ZONE}}/f5aas-gslb-monitor_{{ item.uriHost }}.json"
    branch: ".configuration.gslb_service.monitors"
    leaf: ""
    base: "files.output/gslb-{{GSLB_ZONE}}/f5aas-gslb-update-subscription.tmpl.json"

